// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emojiButton': string;
  'symbolsBody': string;
  'symbolsButton': string;
  'symbolsContainer': string;
  'symbolsFooter': string;
  'symbolsSearch': string;
  'symbolsWindow': string;
}
export const cssExports: CssExports;
export default cssExports;
